name: Sanity Checks

on:
  push:
    branches: ["*"]
  pull_request:

permissions:
  contents: read

jobs:
  compile:
    name: Python compileall
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Run compileall
        run: python -m compileall .
